name: Test Deployment
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  typedoc:
    name: Generate Typedoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/checkout@v4
      - name: Make Typedoc
        run: |
          echo "show PWD (rsvim.github.io)"
          echo $PWD
          echo "ls -la"
          ls -la
          IO_FOLDER="$PWD"

          REPOSITORY="rsvim/rsvim"
          FOLDER="$HOME/.repo/$REPOSITORY"
          echo "REPOSITORY=${REPOSITORY}, FOLDER=${FOLDER}"

          echo "git clone $REPOSITORY"
          git clone --depth=1 --branch=main https://github.com/$REPOSITORY $FOLDER

          rm -rf ./jsruntime
          rm -rf ./generated-typedocs
          cp -rf $FOLDER/src/js/runtime ./jsruntime

          echo "npm install -g typedoc"
          sudo npm install -g typedoc
          echo "npm install"
          npm install
          echo "npm run typedoc"
          npm run typedoc

          rm -rf ./docs/api_references/10__web
          rm -rf ./docs/api_references/50__rsvim
          echo "cp -rf ./generated-typedocs to ./docs/api_references"
          cp -rf ./generated-typedocs/10__web ./docs/api_references
          cp -rf ./generated-typedocs/50__rsvim ./docs/api_references

          echo "git status"
          git status
          echo "tree ./docs/api_references"
          tree ./docs/api_references
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          add-paths: |
            docs/api_references
          commit-message: "chore(typedoc): Auto generate API docs"
          branch-suffix: short-commit-hash
          labels: documentation
      - name: Check Pull Request outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
          echo "Pull Request Branch - ${{ steps.cpr.outputs.pull-request-branch }}"
