name: AutoGen API Docs
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: write
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  typedoc:
    name: Generate Typedoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Make Typedoc
        run: |
          echo "show PWD (rsvim.github.io)"
          echo $PWD
          echo "ls -la"
          ls -la
          IO_FOLDER="$PWD"

          REPOSITORY="rsvim/rsvim"
          FOLDER="$HOME/.repo/$REPOSITORY"
          echo "var REPOSITORY"
          echo $REPOSITORY
          echo "var FOLDER"
          echo $FOLDER

          echo "git clone rsvim repo"
          git clone --depth=1 --branch=main https://github.com/$REPOSITORY $FOLDER
          cd $FOLDER
          echo "show PWD (rsvim)"
          echo $PWD
          echo "ls -la"
          ls -la
          echo "npm install"
          npm install
          echo "npm run typedoc"
          npm run typedoc
          echo "tree generated-typedocs"
          tree generated-typedocs

          cd $IO_FOLDER
          echo "cp $FOLDER/generated-typedocs to ./docs/api_references"
          rm -rf ./docs/api_references/10__web
          rm -rf ./docs/api_references/50__rsvim
          cp -rf $FOLDER/generated-typedocs/10__web ./docs/api_references
          cp -rf $FOLDER/generated-typedocs/50__rsvim ./docs/api_references

          echo "git status"
          git status
          echo "tree docs/api_references"
          tree docs/api_references
      - name: Push Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          add_options: "./docs/api_references"
          commit_message: "chore(api): Auto generate API docs"
          push_options: "--force"
