name: API Docs
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  BRANCH_NAME: generated-typedocs
jobs:
  typedoc:
    name: Generate Typedoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: actions/checkout@v4
      - name: Make Typedoc
        run: |
          echo "show PWD (rsvim.github.io)"
          echo $PWD
          echo "ls -la"
          ls -la
          IO_FOLDER="$PWD"

          REPOSITORY="rsvim/rsvim"
          FOLDER="$HOME/.repo/$REPOSITORY"
          echo "var REPOSITORY"
          echo $REPOSITORY
          echo "var FOLDER"
          echo $FOLDER

          echo "git clone rsvim repo"
          git clone --depth=1 --branch=main https://github.com/$REPOSITORY $FOLDER
          cd $FOLDER
          echo "show PWD (rsvim)"
          echo $PWD
          echo "ls -la"
          ls -la
          echo "npm install"
          npm install
          echo "npm run typedoc"
          npm run typedoc
          echo "tree generated-typedocs"
          tree generated-typedocs

          cd $IO_FOLDER
          echo "cp $FOLDER/generated-typedocs to ./docs/api_references"
          rm -rf ./docs/api_references/10__global
          rm -rf ./docs/api_references/50__rsvim
          cp -rf $FOLDER/generated-typedocs/10__global ./docs/api_references
          cp -rf $FOLDER/generated-typedocs/50__rsvim ./docs/api_references

          echo "git status"
          git status
          echo "tree docs/api_references"
          tree docs/api_references
      - name: Delete Branch
        run: |
          git push -D origin "${BRANCH_NAME}"
      - name: Push Branch
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/api_references"
          default_author: github_actions
          message: "chore(api): Auto generate API docs"
          new_branch: ${{ env.BRANCH_NAME }}
          push: "origin ${BRANCH_NAME} --set-upstream --force"
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore(api): Auto generate API docs"
          branch: ${{ env.BRANCH_NAME }}
          base: main
